### ISSUE TITLE
using metadata from linux doesn't work on mac

### ISSUE THREAD

**Issue by fkowal** [romanowski/hoarder#17] opened 2017-03-03 17:45 UTC
i've tested your plugin on mac and the metadata from linux didn't work

**Comment by romanowski** [comment] 2017-03-03 19:21
It seems that this is caused by jvm's jars not being mapped. So it points to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/rt.jar` form cache from your machine and `/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar` from mine. 

Wiil add mapper.

**Comment by romanowski** [comment] 2017-05-27 08:46
Fixed in #32

**Closed as completed by romanowski** 2017-05-27 08:46 UTC
Labels: hackathon
